project_id = "aougsyziktukjvkmglzb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[functions.poll-tg400]
verify_jwt = false

[functions.test-gateway-connection]
verify_jwt = false

[functions.categorize-sms]
verify_jwt = true

[functions.ai-diagnostics]
verify_jwt = false

[functions.telegram-notify]
verify_jwt = false

[functions.telegram-realtime]
verify_jwt = false
