// This file is automatically generated. Do not edit it directly.
/**
 * API Client for Local SQLite Backend
 * Replaces Supabase with local API using SQLite
 */

export { apiClient as supabase } from './api-client';
export type { Database } from './types';